//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: miVRlink.proto
namespace miVRlink
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position6DofMessage")]
  public partial class Position6DofMessage : global::ProtoBuf.IExtensible
  {
    public Position6DofMessage() {}
    
    private float _timestamp_device;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp_device", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_device
    {
      get { return _timestamp_device; }
      set { _timestamp_device = value; }
    }
    private float _timestamp_system;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp_system", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_system
    {
      get { return _timestamp_system; }
      set { _timestamp_system = value; }
    }
    private float _timestamp_global;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp_global", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_global
    {
      get { return _timestamp_global; }
      set { _timestamp_global = value; }
    }
    private float _px;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"px", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float px
    {
      get { return _px; }
      set { _px = value; }
    }
    private float _py;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"py", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float py
    {
      get { return _py; }
      set { _py = value; }
    }
    private float _pz;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"pz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pz
    {
      get { return _pz; }
      set { _pz = value; }
    }
    private float _qx;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"qx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float qx
    {
      get { return _qx; }
      set { _qx = value; }
    }
    private float _qy;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"qy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float qy
    {
      get { return _qy; }
      set { _qy = value; }
    }
    private float _qz;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"qz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float qz
    {
      get { return _qz; }
      set { _qz = value; }
    }
    private float _qw;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"qw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float qw
    {
      get { return _qw; }
      set { _qw = value; }
    }
    private string _eventId = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string eventId
    {
      get { return _eventId; }
      set { _eventId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResetStatusMessage")]
  public partial class ResetStatusMessage : global::ProtoBuf.IExtensible
  {
    public ResetStatusMessage() {}
    
    private float _timestamp_device;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp_device", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_device
    {
      get { return _timestamp_device; }
      set { _timestamp_device = value; }
    }
    private float _timestamp_system;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp_system", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_system
    {
      get { return _timestamp_system; }
      set { _timestamp_system = value; }
    }
    private float _timestamp_global;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp_global", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_global
    {
      get { return _timestamp_global; }
      set { _timestamp_global = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EyeTrackingMessage")]
  public partial class EyeTrackingMessage : global::ProtoBuf.IExtensible
  {
    public EyeTrackingMessage() {}
    
    private float _timestamp_device;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp_device", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_device
    {
      get { return _timestamp_device; }
      set { _timestamp_device = value; }
    }
    private float _timestamp_system;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp_system", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_system
    {
      get { return _timestamp_system; }
      set { _timestamp_system = value; }
    }
    private float _timestamp_global;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"timestamp_global", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float timestamp_global
    {
      get { return _timestamp_global; }
      set { _timestamp_global = value; }
    }
    private float _basex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"basex", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float basex
    {
      get { return _basex; }
      set { _basex = value; }
    }
    private float _basey;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"basey", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float basey
    {
      get { return _basey; }
      set { _basey = value; }
    }
    private float _basez;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"basez", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float basez
    {
      get { return _basez; }
      set { _basez = value; }
    }
    private float _dirx;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dirx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dirx
    {
      get { return _dirx; }
      set { _dirx = value; }
    }
    private float _diry;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"diry", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float diry
    {
      get { return _diry; }
      set { _diry = value; }
    }
    private float _dirz;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"dirz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float dirz
    {
      get { return _dirz; }
      set { _dirz = value; }
    }
    private float _porx;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"porx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float porx
    {
      get { return _porx; }
      set { _porx = value; }
    }
    private float _pory;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"pory", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pory
    {
      get { return _pory; }
      set { _pory = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}